// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhXtoYwKMCJnhWvkGphFxyZVNSFhRBVBg',
    appId: '1:680334824426:android:5431cc7460fd1208579893',
    messagingSenderId: '680334824426',
    projectId: 'qrcodecreator-ce8b4',
    storageBucket: 'qrcodecreator-ce8b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvMlNv8c5c4xf84u-8wfIlkJMRVN4j4f8',
    appId: '1:680334824426:ios:f3c3ee04309dfee0579893',
    messagingSenderId: '680334824426',
    projectId: 'qrcodecreator-ce8b4',
    storageBucket: 'qrcodecreator-ce8b4.firebasestorage.app',
    androidClientId: '680334824426-5ing8aego98huaf45f9v03ov58k0stfq.apps.googleusercontent.com',
    iosClientId: '680334824426-dai6kbu3oot1joljfeglofkqlsg4isb4.apps.googleusercontent.com',
    iosBundleId: 'com.omerdeveloper.qrcode.qrcodeCreator',
  );

}